"" VUNDLE

  " Utilizamos Vudle como administrador de plugins.

  set backupcopy=yes            " Recomendado para webpack.
  set nocompatible              " Utiliza las opciones avanzadas de vim
  filetype off                  " required

  " set the runtime path to include Vundle and initialize
  set rtp+=~/.vim/bundle/Vundle.vim
  call vundle#begin()
  " alternatively, pass a path where Vundle should install plugins
  "call vundle#begin('~/some/path/here')

  " let Vundle manage Vundle, required
  Plugin 'VundleVim/Vundle.vim'

  " All of your Plugins must be added before the following line
  call vundle#end()            " required
  filetype plugin indent on    " required
  " To ignore plugin indent changes, instead use:
  "filetype plugin on
  "
  " Brief help
  " :PluginList       - lists configured plugins
  " :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
  " :PluginSearch foo - searches for foo; append `!` to refresh local cache
  " :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
  "
  " see :h vundle for more details or wiki for FAQ
  " Put your non-Plugin stuff after this line

""" FUNCIONAMIENTO GENERAL

" turn hybrid line numbers on
:set rnu
:set nu

" set cursorline               " Línea actual subrayada.
set clipboard=unnamedplus      " Copias de vim a PORTAPAPELES
set virtualedit=block          " Permite moverse al cursor por toda la pantalla.
set encoding=utf-8
set helplang=es
set langmenu=es_es.utf8
lan es_ES.utf8
set spell
set spelllang=es
set ttyfast
" Realizar copias de seguridad
" set nobackup		" Don't keep a backup file
set backup
" Directorio para las copias de seguridad
set backupdir=/tmp
" Activamos los plugins
filetype plugin on
" Carácter comodín que utilizan algunos plugins por defecto es la barra
" invertida pero este es más cómodo
let mapleader = ","
" Opciones al guardar sessiones para que no funcione lento al cargarlas
set sessionoptions=curdir,folds,help,tabpages,winsize,winpos
" Linea de estado siempre activada
" ! Cuidado: paste hace que no funcionen las "abbrev".
" set paste	" Compartir porta papeles entre ventanas de vim.
"" Permitir .vimrc en carpetas de proyecto
set exrc
set secure

" Activamos mouse
" Utilizando la techa Shift desactivamos el mouse temporalmente.
set mouse=a
"
" Guardamos historial de cambios.
" Desactivo por crear confusión.
" set undofile
" set undodir=~/.vim/undodir

""" VISUALIZACIÓN
set fillchars=vert:\│
set colorcolumn=80
set sm                             " Visualización de modos
set showcmd                        " Visualización de comandos mientras vamos escribiendo
set showmatch                      " Indica cierre de llaves
" set novisualbell
set noerrorbells
" "set nowrap                      " Evitamos lineas partidas.
set nowrap                           " Evitamos lineas partidas.
set showbreak=\|                   " Shows this string before broken lines
syntax on
syntax enable

""" StatusLine
" set ruler                        " visualizar numero de linea y columna
set laststatus=2                   " Mostramos statusline siempre.
let g:gitparsedbranchname = ' '
function! UpdateGitBranch()
  let l:string = system("git rev-parse --abbrev-ref HEAD 2>/dev/null | tr -d '\n'")
  let g:gitparsedbranchname = strlen(l:string) > 0?'['.l:string.']':''
endfunction

augroup UPDATE_GITBRANCH
    " clear old commands
    autocmd!

    " update git branch
    autocmd BufWritePre * :call UpdateGitBranch()
    autocmd BufReadPost * :call UpdateGitBranch()
    autocmd BufEnter * :call UpdateGitBranch()
augroup END

set statusline=
" set statusline+=%#Visual#             " Color.
" set statusline+=%#StatusLine#         " Color.
set statusline+=%{g:gitparsedbranchname}
set statusline+=\ %f                    " File.
set statusline+=%=                      " Align right.
set statusline+=\ %l:%c                 " Line/column.
hi StatusLine ctermfg=15 cterm=bold ctermbg=8

"Colores"

" Aquí se activa el coloreado de sintaxis (syntax highlighting), además de
" poner algunas opciones adicionales que son cómodas para programar (ver los
" comentarios correspondientes).

" colorscheme edumag2                " Basado en onedark
" colorscheme onedark
" colorscheme solarized

set background=dark
" set background=light

Plugin 'NLKNguyen/papercolor-theme'
colorscheme PaperColor

if has("syntax") || has("gui_running")

    " El resaltado de sintaxis de algunos lenguajes tiene opciones
    " adicionales, aquí activamos las más útiles, sobre todo aquéllas que
    " señalan (normalmente en rojo) ciertos errores de programación.
    let c_gnu                = 1
    let c_space_errors       = 1
    let java_space_errors    = 1
    let ora_space_errors     = 1
    let plsql_space_errors   = 1
    let python_space_errors  = 1
    let python_highlight_all = 1
    let g:sql_type_default   = 'mysql'

endif

highlight Comment ctermfg=Blue
hi Normal guibg=NONE ctermbg=NONE  " Background transparent.

" Con esto Vim señalará con fondo rojo los espacios que queden al final
" de línea: rara vez sirven para algo, así que prefiero poder *verlos*
" para poder quitarlos.
highlight WhitespaceEOL ctermbg=235 guibg=grey50
match WhitespaceEOL /\s\+$/

highlight ColorColumn ctermbg=none ctermfg=red guibg=black guifg=red
call matchadd('ColorColumn', '\%81v', 100) "set column nr

" Color spell.
hi clear SpellBad
hi SpellBad cterm=underline

""" SANGRADO, SALTOS DE LINEA Y TABULADORES

" setlocal textwidth=80          " Limita el ancho a 80 caracteres.
set tabstop=4                    " ancho de tabulador estándar
set softtabstop=4                " ancho que deseamos
set shiftwidth=4                 " ancho del sangrado
"set foldmethod=marker           " Plegar por marcas
set foldmarker={,}               " Marcas con las que plegar
set foldmethod=indent            " Plegar por indent
set autoindent                   " Indentación automática
set expandtab                    " El tabulador utiliza espacios en blanco
filetype indent on	            " Indenta según tipo de archivo
set backspace=indent,eol,start	" more powerful backspacing
set smartindent

""" BÚSQUEDAS

" set nohlsearch         " No ilumina las búsquedas encontradas
set hlsearch             " Ilumina las búsquedas encontradas
set ignorecase smartcase " Ignora mayúsculas en búsquedas salvo si se escribe en mayúsculas.
set incsearch            " Búsqueda incremental

""" COMANDOS PROPIOS

" Borrado automático de espacios en blanco.
autocmd BufWritePre * :%s/\s\+$//e

" Cerrado automatico.
inoremap { {}<Esc>ha
inoremap ( ()<Esc>ha
inoremap [ []<Esc>ha
inoremap " ""<Esc>ha
inoremap ' ''<Esc>ha
inoremap ` ``<Esc>ha

" Autocompletado.
""" find /usr/share/vim -iname "*complete*.vim" -exec basename {} \;
""" Con Ctr-x Ctrl-o
""" Sintaxis para HTML
:set omnifunc=htmlcomplete#CompleteTags
" Sintaxis para CSS
:set omnifunc=csscomplete#CompleteCSS
" Sintaxis para JavaScript
:set omnifunc=javascriptcomplete#CompleteJS
" Sintaxis para PHP
:set omnifunc=phpcomplete#CompletePHP
" Sintaxis para Python 3
:set omnifunc=python3complete#Complete
" Activar sintaxis completa
:set omnifunc=syntaxcomplete#Complete

" Suffixes that get lower priority when doing tab completion for filenames.
" These are files we are not likely to want to edit or read.
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc
command Incloura !$HOME/desarrollo/magtrabajos/magtrabajos -a %
command Console grep -r 'console\.' src/
command OnlyThis grep -r '@onlyThis' test/
command TODO grep -r -E "@todo\|@bug" src/ test/

" AUTOCOMMAND
" En Vim se pueden definir comandos que se ejecutan automáticamente cuando
" una determinada cosa ocurre. Este ejemplo hace que al cargar un fichero
" que se había editado previamente se posiciones el cursor la línea en que
" estaba cuando se dejó de editar por última vez. Muy cómodo :-)

if has("autocmd")
    autocmd BufReadPost *
                \ if line("'\"") > 0 && line("'\"") <= line("$") |
                \		execute "normal g'\"" |
                \ endif
endif

" Al abrir fichero desplegar.
autocmd BufWinEnter * silent! :%foldopen!

" Forzar detectar archivos .md como markdown.
au BufNewFile,BufFilePre,BufRead *.md set filetype=markdown

" Syntax para rst
au BufNewFile,BufRead *.rst set ft=rest

" Syntax para html
au BufNewFile,BufRead *html set ft=xml

au BufRead,BufNewFile *.txt :setlocal spell
au BufRead,BufNewFile *.md :setlocal spell
au BufRead,BufNewFile *.rst :setlocal spell

" Guardar sesión.
au VimLeavePre * if v:this_session != '' | exec "mks! " . v:this_session | endif

map <F1> :new $HOME/.vim/README.md<CR>

" Abrimos nerdtree al inicio.
" autocmd VimEnter * NERDTreeFind
" Toggle NERDTree
map <F2> :NERDTreeToggle<CR>
imap <F2> <Esc>:NERDTreeToggle<CR>

" Configuramos nerdtree_open
" nerdtree_plugin/nerdtree_open.vim
let g:nerdtree_open_cmd = 'xdg-open'

" Cerrar nerdtree automáticamente al abrir fichero.
let NERDTreeQuitOnOpen=1

""" TEMPLATES
inoreabbrev <h. <Esc>:r ~/.vim/templates/skeleton.html<cr><Esc>ggdd
inoreabbrev <d. <LT>div><cr><LT>/div><Esc>O
inoreabbrev __CD console.dir({ data: data }, { depth: null })<Esc>26h

""" PROGRAMACIÓN

" Barra de etiquetas a la derecha.
let Tlist_Use_Right_Window = 1

" Lista errores
map <F11> :cp<CR>
map <F12> :cn<CR>
map <C-W><C-Right> :vertical resize +35<CR>
map <C-W><C-Left> :vertical resize -35<CR>
map <C-W><C-Up> :horizontal resize -35<CR>
map <C-W><C-Down> :horizontal resize +35<CR>
map <C-W><S-Right> :vertical resize +15<CR>
map <C-W><S-Left> :vertical resize -15<CR>
map <C-W><S-Up> :horizontal resize -15<CR>
map <C-W><S-Down> :horizontal resize +15<CR>

" Ver documentación de php.
" Con ponerte sobre una función y pulsar ‘K’ mayúscula tendrás la documentación
" correspondiente.
" Instalar la documentación en el sistema.
" sudo pear install doc.php.net/pman
" set keywordprg=terminator\ -x\ pman
set keywordprg=pman

if has("autocmd")
" Drupal *.modules files.
augroup module
  autocmd BufRead *.dox set filetype=java.doxygen
augroup END
augroup module
  autocmd BufRead *.inc set filetype=php
augroup END
augroup module
  autocmd BufRead *.install set filetype=php
augroup END
augroup module
  autocmd BufRead *.module set filetype=php
augroup END
augroup engine
  autocmd BufRead *.engine set filetype=php
augroup END
augroup profile
  autocmd BufRead *.profile set filetype=php
augroup END
augroup test
  autocmd BufRead *.test set filetype=php
augroup END
endif

if !exists("autocommads_loaded")
    let autocommads_loaded = 1
    " autocmd FileType html set omnifunc=htmlcomplete#CompleteTags#Html " @todo Da error falta la función.
    autocmd FileType php call Php()
    autocmd FileType javascript call Php()
    autocmd FileType txt call Txt()
    autocmd FileType rst call Rst()
    autocmd FileType rest call Txt()
    autocmd FileType sh call Sh()
    autocmd FileType css set omnifunc=csscomplete#CompleteCSS
endif

" Autocommands para PHP
function Php()

    setlocal textwidth=80 " Limita el ancho a 80 caracteres.
    " Compilador tidy
    " compiler tidy
    " UTF8 para archivos php
    " set encoding=utf8
    " Con esta opción el texto sera cortado en la columna indicada por
    " *textwidth* con formatoptions=croql hara que el codigo fuente no sea
    " formateado pero si los comentarios
    setlocal fo-=t fo+=croql
    " Don't concatenate a line that ends with a backslash
    setlocal cpo-=C
    set autoindent " Indentación automatica

    " Revisamos sintaxis con php.
    ""set makeprg=php\ -l\ %
    ""set errorformat=%m\ in\ %f\ on\ line\ %l,%-GErrors\ parsing\ %f,%-G
    ""if filereadable("phpstan_Muy_lento")
    ""    " Descartamos, es muy lento.
    ""    set errorformat=%f:%l:%m
    ""    set makeprg=./phpstan\ %
    ""endif
    " Instalado phpLint.vim para que ejecute php -l tras guardar.

    " Abreviaturas
    inoreabbrev _USE_LOG use Illuminate\Support\Facades\Log;
    inoreabbrev _LOG Log::debug('');<Esc>3h

    " Con Ctrl-T comentamos la linea y la copiamos abajo
    map <C-T> <Esc>yyg^i// <Esc>pi

endfunction

function Rst()
    setlocal textwidth=80 " Limita el ancho a 80 caracteres.
    setlocal fo=cqt
    setlocal wm=1
endfunction

function Txt()
    setlocal textwidth=80 " Limita el ancho a 80 caracteres.
    setlocal fo=cqt
    setlocal wm=1
endfunction

function Sh()
    set foldmethod=marker  " Plegar por marcas
    "set foldmethod=indent  " Plegar por indent
    setlocal textwidth=0 " Quita limitacion de caracteres.
    " Con Ctrl-T comentamos la linea y la copiamos abajo
    map <C-T> <Esc>yyg^i# <Esc>pi
    " Ejecutar el script editado con ALT-e, sirve para scripts bash
    noremap! å :w :!%

endfunction

" yaml
autocmd FileType yaml setlocal ts=4 sts=4 sw=4 expandtab

" python
autocmd FileType python set sw=4
autocmd FileType python set ts=4
autocmd FileType python set sts=4
" AutoPep8, dando formato a python.
" sudo pip install autopep8
" Seleccionamos texto y tecleamos "gq".
au FileType python setlocal formatprg=autopep8\ -

""" COLORES EN CSS

  "Is used when updatetime value set by plugin (100ms)
  "is interfering with your configuration.
  " g:cssColorVimDoNotMessMyUpdatetime
  let g:cssColorVimDoNotMessMyUpdatetime = 1

""" PLUGINS

" PHP_CodeSniffer.
" Plugin 'phpcs.vim'
" Activamos revisión de código Al leer o guardar fichero.
" "autocmd BufWritePre *.php :Phpcs
" let g:phpcs_std_list   = "PSR2"
" let g:phpcs_max_output = 0 " Unlimited output.

" AIRLINE
" Plugin 'vim-airline/vim-airline'
" Plugin 'vim-airline/vim-airline-themes'
" let g:airline_theme='angr'
" let g:airline_powerline_fonts=1
" " Habilita los tabs, para cambiar de tab presionar gt
" let g:airline#extensions#tabline#enabled = 0
" " Enable the list of buffers
" let g:airline#extensions#tabline#show_buffers = 0
" let g:airline#extensions#tabline#show_tabs = 0
" " set t_Co=256
" let g:airline#extensions#branch#enabled=0
" let g:airline#extensions#hunks#enabled=0
"   " let g:airline_extensions = ['branch', 'tabline']

" Debug
" Plugin 'joonty/vdebug'

" Python Mode.
" Desactivamos temporalmente.
"   Plugin 'Python-mode-klen'
"   let g:pymode_options = 0
"   let g:pymode_lint = 1
"   " let g:pymode_lint_ignore="E302,E266,W0401,E501,C901,E221"
"   let g:pymode_trim_whitespaces = 1
"   setlocal complete+=t
"   setlocal formatoptions-=t
"   " if v:version > 702 && !&relativenumber
"   "     setlocal nonumber
"   " endif
"   setlocal textwidth=79
"   setlocal commentstring=#%s
"   setlocal define=^\s*\\(def\\\\|class\\)
"   let g:pymode_virtualenv = 1

" Varios.
" Plugin 'rest.vim'
" Plugin 'sukima/xmledit'

" Plugin 'chrisbra/csv.vim'
" let did_load_csvfiletype=1
" au BufNewFile,BufFilePre,BufRead *.csv set filetype=csv

" Typescript
" https://www.vimfromscratch.com/articles/setting-up-vim-for-typescript
"" Plugin 'leafgarland/typescript-vim'
"" " let g:typescript_indent_disable = 1
"" au BufNewFile,BufFilePre,BufRead *.ts set filetype=typescript
"" Plugin 'sbdchd/neoformat'
"" autocmd FileType typescript setlocal formatprg=prettier\ --parser\ typescript
"" " Ale
"" " Demasiados recursos, desactivo.
"" " Plugin 'w0rp/ale'
"" " let g:ale_fixers = {}
"" " let g:ale_fixers.javascript = ['eslint']
"" " let g:ale_fix_on_save = 1

" Colores css.
Plugin 'ap/vim-css-color'

" blade
Plugin 'jwalton512/vim-blade'

" React.
Plugin 'MaxMEllon/vim-jsx-pretty'

"" Vue
" Vim syntax highlighting for [Vue
" Desactivado temporalmente.
" Plugin 'posva/vim-vue'
" " let g:vue_pre_processors = 'detect_on_enter'
" if has("autocmd")
"     augroup vue
"       autocmd BufRead *.vue set filetype=vue
"     augroup END
" endif
" " Syntax and indent plugin.
" Plugin 'leafOfTree/vim-vue-plugin'
" let g:vim_vue_plugin_config_load_full_syntax = 1
" let g:vim_vue_plugin_config_use_typescript = 0


" https://dev.to/iggredible/how-to-search-faster-in-vim-with-fzf-vim-36ko
Plugin 'junegunn/fzf.vim'
Plugin 'junegunn/fzf', { 'do': { -> fzf#install() } }
" Buscar ficheros.
nnoremap <silent> <C-f> :Files<CR>
" Buscar en ficheros.
" Dependencias. sudo apt  install ripgrep
nnoremap <silent> <Leader>f :Rg<CR>
" Etiquetas :Tags <tag>

" Mostrar indent.
Plugin 'yggdroot/indentline'

" Nos centramos en ventana actual y volvemos a todas las ventanas.
" https://github.com/szw/vim-maximizer
Plugin 'szw/vim-maximizer.git'
nnoremap <silent><F3> :MaximizerToggle<CR>
vnoremap <silent><F3> :MaximizerToggle<CR>gv
inoremap <silent><F3> <C-o>:MaximizerToggle<CR>

" Ampliamos detección de bloques.
" https://github.com/andymass/vim-matchup#detailed-feature-documentation
Plugin 'andymass/vim-matchup'
:hi MatchParen ctermfg=7 ctermbg=2

" Diagnostics (via Language Server Protocol linters)
"
" - Go To Definition (:ALEGoToDefinition)
" - Completion (Built in completion support, or with Deoplete)
" - Finding references (:ALEFindReferences)
" - Hover information (:ALEHover)
" - Symbol search (:ALESymbolSearch)
"
" https://github.com/dense-analysis/ale
Plugin 'dense-analysis/ale'
let g:ale_lint_on_text_changed=0
let g:ale_lint_on_insert_leave=0
let g:ale_lint_on_save=1
let g:ale_fix_on_save = 0
" let g:ale_echo_msg_error_str = 'E'
" let g:ale_echo_msg_warning_str = 'W'
let g:ale_sign_error = ' '
let g:ale_sign_warning = '⚠ '
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_python_flake8_options = '--max-line-length 88 --extend-ignore=E203'
" ALE omni-completion completion manually with <C-x><C-o>.
let g:ale_completion_enabled = 1
" Only run linters named in ale_linters settings.
let g:ale_linters_explicit = 0
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 0
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_delay = 1000
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 0
let g:ale_set_balloons=1
set omnifunc=ale#completion#OmniFunc
let g:ale_virtualtext_cursor = 'current'
let g:ale_set_highlights = 1
let g:ale_disable_lsp = 0
let g:ale_hover_cursor = 1
let g:ale_hover_to_preview = 1
let g:ale_hover_to_floating_preview = 1
let g:ale_floating_window_border = ['│', '─', '╭', 'Z', '╯', '╰', '│', '─']
let g:ale_floating_window_position = 'topright'
let g:ale_echo_delay = 1000
let g:ale_completion_autoimport = 1
let g:ale_set_balloons = 1

" Color hover
""hi ALEErrorSign ctermbg=NONE ctermfg=1
""hi ALEWarningSign ctermbg=NONE ctermfg=3
""hi ALEInfoSign ctermbg=NONE ctermfg=4
highlight Pmenu ctermbg=black ctermfg=white

set updatetime=3000

" Mostramos información del símbolo en el cursor automáticamente.
""augroup ale_hover_cursor
""  autocmd!
""  autocmd CursorHold * ALEHover
""augroup END

" PHP
" Linter para json.
" npm install -g @biomejs/biome
let g:ale_linters = {
    \ 'php': ['phpcs', 'phpstan', 'phpactor'],
    \ 'javascriptreact': ['eslint'],
    \ 'markdown': ['mdl'],
    \ 'sh': ['shellcheck'],
    \'javascript': ['eslint'],
    \'typescript': ['tslint', 'tsserver', 'prettier'],
    \'python': ['pylsp']
\}
let g:ale_fixers = {
    \ 'php': ['phpcbf'],
    \'javascript': ['eslint'],
    \'json': ['prettier'],
    \'yaml': ['prettier'],
    \'typescript': ['tslint', 'prettier'],
    \'markdown': ['prettier'],
    \'python': ['autopep8']
\}

" Keybindings para ALE.
noremap <silent><F4> :ALEGoToDefinition<CR>
noremap <silent><F5> :ALEPopulateQuickfix<CR>:copen<CR>
noremap <silent><F6> :ALEHover<CR>
noremap <silent><F7> :ALESymbolSearch<CR>
noremap <silent><F8> :ALEFindReferences<CR>

let g:ale_linters_ignore = []

let g:ale_php_phpstan_executable = './vendor/phpstan/phpstan/phpstan analyse --ansi --memory-limit 512M '

""" Barra de estado.
" Mostrar rama de git en barra de estado.
Plugin 'itchyny/vim-gitbranch'
" https://github.com/itchyny/lightline.vim
Plugin 'itchyny/lightline.vim'
" https://github.com/maximbaz/lightline-ale
Plugin 'maximbaz/lightline-ale'
"    \ 'colorscheme': 'onedark',
let g:lightline = {
    \ 'colorscheme': 'PaperColor',
    \}
" Función personalizada para obtener el path relativo del fichero.
function! LightLineFilename()
    let filename = expand('%:f') !=# '' ? expand('%:f') : '[No Name]'
    let modified = &modified ? ' +' : ''
    return filename . modified
	let name = ""
	let subs = split(expand('%'), "/")
	let i = 1
	for s in subs
		let parent = name
		if  i == len(subs)
			let name = parent . '/' . s
		elseif i == len(subs) - 1
			let name = parent . '/' . s
		elseif i == 1
			let name = s
		else
			let name = parent . '/' . strpart(s, 0, 4)
		endif
		let i += 1
	endfor
  return name
endfunction
function! LightLineReadonly()
    return &filetype =~ s:ignore_types || &readonly ? '' :&filetype ==  ''
endfunction
function! LightLineModified()
    return &filetype !~s:ignore_types && &modified ? '+' : ''
endfunction

let s:label = '%{substitute(expand("%"), "NetrwTreeListing \\d\\+", "netrw", "")}'
let g:lightline.component_expand = {
      \ 'linter_checking': 'lightline#ale#checking',
      \ 'linter_infos': 'lightline#ale#infos',
      \ 'linter_warnings': 'lightline#ale#warnings',
      \ 'linter_errors': 'lightline#ale#errors',
      \ 'linter_ok': 'lightline#ale#ok',
      \ 'gitbranch': 'gitbranch#name',
      \ 'modified': '%{&filetype == "help" ? "" : &modified ? "+" : &modifiable ? "" : "-"}',
      \ 'label': s:label
      \ }

let g:lightline.tabline = {
    \ 'left': [ [ 'tabs' ] ],
    \ 'right': [ ] }
let g:lightline.tab = {
    \ 'active': [ 'filename', 'modified' ],
    \ 'inactive': [ 'filename', 'modified' ]
  \ }
let g:lightline.component_function = {
      \ 'filename': 'LightLineFilename',
  \ }
let g:lightline.inactive = {
    \ 'left': [
    \           [ 'gitbranch', 'readonly', 'filename' ],
    \           [ 'modified', 'label' ]
    \         ],
    \ 'right': [ [ 'linter_checking', 'linter_errors', 'linter_warnings', 'linter_infos', 'linter_ok' ],
    \            [ 'lineinfo' ],
    \            [ 'percent' ],
    \            [ 'fileformat', 'fileencoding', 'filetype']
    \          ],
    \ }

let g:lightline.active = {
    \ 'left': [ [ 'mode', 'paste' ],
    \           [ 'gitbranch', 'readonly', 'filename' ],
    \           [ 'modified', 'label' ]
    \         ],
    \ 'right': [ [ 'linter_checking', 'linter_errors', 'linter_warnings', 'linter_infos', 'linter_ok' ],
    \            [ 'lineinfo' ],
    \            [ 'percent' ],
    \            [ 'fileformat', 'fileencoding', 'filetype']
    \          ],
    \ }

let g:lightline#ale#indicator_checking = "\uf110 "
let g:lightline#ale#indicator_infos = "\uf129 "
let g:lightline#ale#indicator_warnings = "\uf071 "
let g:lightline#ale#indicator_errors = "\uf05e "
let g:lightline#ale#indicator_ok = "\uf00c "

" Iconos.
Plugin 'ryanoasis/vim-devicons'
" let g:webdevicons_conceal_nerdtree_brackets = 1
exec 'autocmd filetype nerdtree syntax match hideBracketsInNerdTree "[\]|\[]*" contained conceal cchar=_ containedin=ALL'
""exec 'autocmd filetype nerdtree set conceallevel=3'
""exec 'autocmd filetype nerdtree set concealcursor=nvic'

" PhpStan
" Script phpstan en proyecto.
"    # https://phpstan.org/user-guide/rule-levels
"    # make exec c="vendor/phpstan/phpstan/phpstan $@"
"    docker-compose run app ./vendor/phpstan/phpstan/phpstan analyse --ansi -l 1 --memory-limit 512M --no-progress --error-format=raw $@ \
"        | sed 's/\/var\/www\///'
" Configuración de phpstan en phpstan.neon.dist
" Ejecutar phpstan sobre fichero actual.
nmap <leader>pa :let &errorformat = '%f:%l:%m'<cr>:cexpr system('./phpstan ' . expand("%"))<cr>:copen<cr>
" Ejecutar phpstan en proyecto.
nmap <leader>pt :let &errorformat = '%f:%l:%m'<cr>:cexpr system('./phpstan ')<cr>:copen<cr>

""" ERRORES AL ESCRIBIR """
""""" TYPESCRIPT
""" autocomplete list
""set wildmenu
""set wildmode=list:full
""
""" ALE
""let g:ale_emit_conflict_warnings = 0
""let g:ale_sign_column_always = 1
""let g:ale_completion_enabled = 0
""let g:ale_completion_tsserver_autoimport = 0
""
""" asyncomplete
""" preferred keyboard mappings for navigating autocomplete menu
""inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
""inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
""inoremap <expr> <cr>    pumvisible() ? "\<C-y>\<cr>" : "\<cr>"
""inoremap <expr> <Esc>   pumvisible() ? "\<C-y>\<Esc>" : "\<Esc>"
""imap <c-space> <Plug>(asyncomplete_force_refresh)
""
""" autocomplete
""set completeopt+=menuone,preview
""
""""call asyncomplete#register_source(asyncomplete#sources#buffer#get_source_options({
""""    \ 'name': 'buffer',
""""    \ 'whitelist': ['*'],
""""    \ 'completor': function('asyncomplete#sources#buffer#completor'),
""""    \ 'config': {
""""    \    'max_buffer_size': 5000000,
""""    \  },
""""    \ }))
""
""" need to do
""" npm install -g javascript-typescript-langserver
""" for this to work
""if executable('javascript-typescript-stdio')
""  au User lsp_setup call lsp#register_server({
""    \ 'name': 'javascript-typescript-stdio',
""    \ 'cmd': {server_info->['javascript-typescript-stdio']},
""    \ 'whitelist': ['typescript', 'javascript', 'typescript.tsx'],
""    \ })
""endif
""
""set omnifunc=ale#completion#OmniFunc
""
""" vimexecutor
""" Executeu codi, compileu, maximitzeu les finestres, canvieu el nom de les
""" finestres, feu zoom, canvieu la mida de finestres/terminals, executeu ordres
""" i molt més amb només 1 clic!
""" "Plugin 'mctechnology17/vim-executor'
""
""" Depuración
""""Plugin 'puremourning/vimspector'
""let g:vimspector_enable_mappings = 'HUMAN'
""""nnoremap <Leader>dd :call vimspector#Launch()<CR>
""""nnoremap <Leader>de :call vimspector#Reset()<CR>
""""nnoremap <Leader>dc :call vimspector#Continue()<CR>
""""
""""nnoremap <Leader>dt :call vimspector#ToggleBreakpoint()<CR>
""""nnoremap <Leader>dT :call vimspector#ClearBreakpoints()<CR>
""""
""""nmap <Leader>dk <Plug>VimspectorRestart
""""nmap <Leader>dh <Plug>VimspectorStepOut
""""nmap <Leader>dl <Plug>VimspectorStepInto
""""nmap <Leader>dj <Plug>VimspectorStepOver

"" Project lint (nerdtree)
" https://github.com/kristijanhusak/vim-project-lint?tab=readme-ov-file
Plugin 'kristijanhusak/vim-project-lint'
let g:project_lint#error_icon = ' '
let g:project_lint#warning_icon = '⚠ '
let g:project_lint#error_icon_color = 'guifg=#fb4934 ctermfg=167'
let g:project_lint#warning_icon_color = 'ctermfg=214 guifg=#fabd2f'
" Echo linting progress in command line. Another way to get the progress info is to use statusline.
" example:
" set statusline+=project_lint#statusline()
let g:project_lint#echo_progress = v:true
"Linter settings
"example:
" let g:project_lint#enabled_linters = {'javascript': ['eslint'], 'python': ['mypy']}
" If there's no setting provided for filetype, all available linters are used.
" If provided an empty array fora filetype, no linting is done for it.
" let g:project_lint#pylsp = {}
" Para que funcione con typescript hay que instalar tslint.
" Y ejecutar tslint --init.
let g:project_lint#enabled_linters = {
      \ 'javascript': ['eslint'],
      \ 'typescript': ['tslint'],
      \ 'json': ['jq'],
      \ 'python': ['pylsp']
      \ }
"let g:project_lint#linter_args = {'mypy': '--ignore-missing-imports'}
let g:project_lint#linter_args = {'tslint': '-p .'}
"Folder settings
"Lint status is cached for each project in this folder.
let g:project_lint#cache_dir = '~/.cache/vim-project-lint'
" When this is left empty, all folders from $HOME and above are ignored and not linted:
" example of empty value: `['/home/kristijan', '/home', '/']`
" To allow linting these folders (not recommended), set this value to `v:false`
" Or use your own list of folders. When non-empty value is provided, above defaults are not added.
let g:project_lint#ignored_folders = ['node_modules/', '.git/', '.mypy_cache', 'venv/', 'dist/', 'docs/', 'build/']
"Other
" Echo linting progress in command line. Another way to get the progress info is to use statusline.
" example:
" set statusline+=project_lint#statusline()
let g:project_lint#echo_progress = v:true
" Prints all calls to linter commands and their responses. Mostly useful for development.
" let g:project_lint#debug = v:true

" https://github.com/mbbill/undotree
Plugin 'mbbill/undotree'
if has("persistent_undo")
   let target_path = expand('~/.local/state/vim/undodir')

    " create the directory and any parent directories
    " if the location does not exist.
    if !isdirectory(target_path)
        call mkdir(target_path, "p", 0700)
    endif

    let &undodir=target_path
    set undofile
endif

" Terminal in vim
" nmap <leader>t :below horizontal terminal<CR>
nmap <leader>t :let $VIM_DIR=expand('%:p:h')<CR>:below horizontal terminal<CR>cd $VIM_DIR<CR>

" Repetir cualquier comando.
Plugin 'tpope/vim-repeat'
silent! call repeat#set("\<Plug>MyWonderfulMap", v:count)

" Logs view.
autocmd BufNewFile,BufRead *.txt set filetype=json

" vimserver
Plugin 'https://github.com/wolandark/vim-live-server.git'
Plugin 'nikvdp/ejs-syntax'

Plugin 'https://github.com/airblade/vim-gitgutter.git'

""" AI

"" vim-ollama
"" Funciona pero muy lento.
" Plugin 'gergap/vim-ollama'
" let g:ollama_debounce_time = 300

"" codeium
Plugin 'Exafunction/codeium.vim'
" Codeium provides the following functions to control suggestions:
" Clear current suggestion	codeium#Clear()	<C-]>
" Next suggestion	codeium#CycleCompletions(1)	<M-]>
" Previous suggestion	codeium#CycleCompletions(-1)	<M-[>
" Insert suggestion	codeium#Accept()	<Tab>
" Manually trigger suggestion	codeium#Complete()	<M-Bslash>
" Accept word from suggestion	codeium#AcceptNextWord()	<C-k>
" Accept line from suggestion	codeium#AcceptNextLine()	<C-l>
" Codeium's default keybindings can be disabled by setting
""let g:codeium_server_config = {
""\    'api_url': s:url_ai
""\}
let g:codeium_disable_bindings = 0
imap <C-c>   <Cmd>call codeium#CycleCompletions(1)<CR>
imap <C-z>   <Cmd>call codeium#CycleCompletions(-1)<CR>
imap <C-x>   <Cmd>call codeium#Clear()<CR>

" https://github.com/madox2/vim-ai
Plugin 'madox2/vim-ai'
Plugin 'madox2/vim-ai-provider-google'

"" AI - CONFIG

" vim-ai
let g:vim_ai_roles_config_file = '~/.vim/vim-ai-roles.ini'

"" ollama
" let s:model_ai = "deepseek-coder-v2:latest"
" let s:url_ai = "http://127.0.0.1:11434"
"" deepseek
" let s:model_ai = "deepseek-chat"
" let s:url_ai = "https://api.deepseek.com"
" let s:api_key = $DEEPSEEK_API_KEY
"" LMStudio
" let s:model_ai = "deepseek-coder-v2-lite-instruct"
" let s:url_ai = "http://192.168.100.149:1234"
"" openrouter
let s:model_ai = "deepseek/deepseek-chat-v3-0324:free"
let s:url_ai = "https://openrouter.ai/api"
let s:api_key = $OPENROUTER_API_KEY
let g:vim_ai_token_file_path = '~/.config/openai.token'

" enables/disables full markdown highlighting in aichat files
" NOTE: code syntax highlighting works out of the box without this option enabled
" NOTE: highlighting may be corrupted when using together with the `preservim/vim-markdown`
let g:vim_ai_chat_markdown = 1

" debug settings
let g:vim_ai_debug = 1
let g:vim_ai_debug_log_file = "/tmp/vim_ai_debug.log"

" This prompt instructs model to be consise in order to be used inline in editor
let s:initial_complete_prompt =<< trim END
>>> system

You are a general assistant.
Answer shortly, consisely and only what you are asked.
Do not provide any explanantion or comments if not requested.
If you answer in a code, do not wrap it in markdown code block.
END

let g:vim_ai_complete = {
\  "prompt": "",
\  "options": {
\    "model": s:model_ai,
\    "endpoint_url": s:url_ai . "/v1/chat/completions",
\    "api_key_name": s:api_key,
\    "max_tokens": 0,
\    "num_ctx": 163840,
\    "max_completion_tokens": 0,
\    "temperature": 1,
\    "request_timeout": 200,
\    "stream": 1,
\    "selection_boundary": "#####",
\    "initial_prompt": s:initial_complete_prompt,
\  },
\  "ui": {
\    "paste_mode": 1,
\  },
\}

let g:vim_ai_edit = {
\  "prompt": "",
\  "options": {
\    "model": s:model_ai,
\    "endpoint_url": s:url_ai . "/v1/chat/completions",
\    "auth_type": "bearer",
\    "max_tokens": 0,
\    "num_ctx": 163840,
\    "max_completion_tokens": 0,
\    "temperature": 0.1,
\    "request_timeout": 200,
\    "stream": 1,
\    "selection_boundary": "#####",
\    "initial_prompt": s:initial_complete_prompt,
\  },
\  "ui": {
\    "paste_mode": 1,
\  },
\}


" This prompt instructs model to work with syntax highlighting
let s:initial_chat_prompt =<< trim END
>>> system

Eres un experto desarrollador de código, experto en buenas practicas.

Si añades bloques de código hazlo con formato makdown, Añadiendo ``` para obtener colores.

Si puedes contesta en castellano.
END

" :AIChat
" - provider: AI provider
" - prompt: optional prepended prompt
" - options: openai config (see https://platform.openai.com/docs/api-reference/chat)
" - options.initial_prompt: prompt prepended to every chat request (list of lines or string)
" - options.temperature: use -1 to disable this parameter
" - options.request_timeout: request timeout in seconds
" - options.auth_type: API authentication method (bearer, api-key, none)
" - options.token_file_path: override global token configuration
" - options.token_load_fn: expression/vim function to load token
" - options.selection_boundary: selection prompt wrapper (eliminates empty responses, see #20)
" - ui.open_chat_command: preset (preset_below, preset_tab, preset_right) or a custom command
" - ui.populate_options: dump [chat] config to the chat header
" - ui.scratch_buffer_keep_open: re-use scratch buffer within the vim session
" - ui.force_new_chat: force new chat window (used in chat opening roles e.g. `/tab`)
" - ui.paste_mode: use paste mode (see more info in the Notes below)
let g:vim_ai_chat = {
\  "prompt": "",
\  "options": {
\    "model": s:model_ai,
\    "endpoint_url": s:url_ai . "/v1/chat/completions",
\    "api_key": s:api_key,
\    "auth_type": "bearer",
\    "max_tokens": 0,
\    "num_ctx": 163840,
\    "max_completion_tokens": 0,
\    "temperature": 1,
\    "request_timeout": 1000,
\    "stream": 1,
\    "selection_boundary": "",
\    "initial_prompt": s:initial_chat_prompt,
\  },
\  "ui": {
\    "open_chat_command": "preset_below",
\    "scratch_buffer_keep_open": 0,
\    "populate_options": 0,
\    "force_new_chat": 0,
\    "paste_mode": 1,
\  },
\}

let g:vim_ai_image = {
\  "prompt": "",
\  "options": {
\    "endpoint_url": s:url_ai . "/v1/chat/completions",
\    "model": "mistralai/mistral-small-3.2-24b-instruct:free",
\    "quality": "standard",
\    "size": "1024x1024",
\    "style": "vivid",
\    "request_timeout": 400,
\    "api_key": s:api_key,
\    "auth_type": "bearer"
\  },
\  "ui": {
\    "download_dir": "~/Imágenes/",
\  },
\}

" custom command suggesting git commit message, takes no arguments
function! GitCommitMessageFn()
  let l:range = 0
  let l:diff = system('git --no-pager diff --staged')
  let l:prompt = "generate a short commit message from the diff below:\n" . l:diff
  let l:config = {
  \  "options": {
  \    "model": s:model_ai,
  \    "initial_prompt": ">>> system\nyou are a code assistant",
  \    "temperature": 1,
  \  },
  \}
  call vim_ai#AIRun(l:range, l:config, l:prompt)
endfunction
command! GitCommitMessage call GitCommitMessageFn()


" custom command that provides a code review for selected code block
function! CodeReviewFn(range) range
  let l:prompt = "El código es " . &filetype . ", revisa que utlice buenas practicas y clean code"
  let l:config = {
  \  "options": {
  \    "initial_prompt": ">>> system\nEres un experto programador que utiliza clean code.",
  \  },
  \}
  exe a:firstline.",".a:lastline . "call vim_ai#AIChatRun(a:range, l:config, l:prompt)"
endfunction
command! -range -nargs=? AICodeReview <line1>,<line2>call CodeReviewFn(<range>)
