" VUNDLE

  " Utilizamos Vudle como administrador de plugins.

  set backupcopy=yes " Recomendado para webpack.
	set nocompatible              " be iMproved, required
	filetype off                  " required

	" set the runtime path to include Vundle and initialize
	set rtp+=~/.vim/bundle/Vundle.vim
	call vundle#begin()
	" alternatively, pass a path where Vundle should install plugins
	"call vundle#begin('~/some/path/here')

	" let Vundle manage Vundle, required
	Plugin 'VundleVim/Vundle.vim'

	" All of your Plugins must be added before the following line
	call vundle#end()            " required
	filetype plugin indent on    " required
	" To ignore plugin indent changes, instead use:
	"filetype plugin on
	"
	" Brief help
	" :PluginList       - lists configured plugins
	" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
	" :PluginSearch foo - searches for foo; append `!` to refresh local cache
	" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
	"
	" see :h vundle for more details or wiki for FAQ
	" Put your non-Plugin stuff after this line

" FUNCIONAMIENTO GENERAL
       
  set nonumber " Ocultamos número de linea en archivo.
  :map <F3> :tabn<cr>
  set nowrap " Evitamos lineas partidas.
  set virtualedit=block " Permite moverse al cursor por toda la pantalla.
	set encoding=utf-8
	set nocompatible " Utiliza las opciones avanzadas de vim
	set helplang=es
	set langmenu=es_es.utf8
	lan es_ES.utf8
	set spell
	set spelllang=es
	set ttyfast
	" Realizar copias de seguridad
	" set nobackup		" Don't keep a backup file
	set backup
	" Directorio para las copias de seguridad
	set backupdir=/tmp
	" Enviar al portapapeles todo lo que copiemos
	set clipboard=unnamed
	" Activamos los plugins
	filetype plugin on
	" Caracter comodin que utilizan algunos plugins por defecto es la barra
	" invertida pero este es más comodo
	let mapleader = ","
	" Opciones al guardar sessiones para que no funcione lento al cargarlas
	set sessionoptions=buffers,curdir,folds,options
	" Linea de estado siempre activada
	set laststatus=2
	" Tamaño del historial de comandos
	set history=50 
	set paste	" Compartir porta papeles entre ventanas de vim.         
  " Permitir .vimrc en carpetas de proyecto
	set exrc
	set secure

" VISUALIZACIÓN

  set colorcolumn=80
	set background=dark
	"set background=light
	" colorscheme edumag " Colores personalizados
	set sm " Visualización de modos
	set showcmd " Visualización de comandos mientras vamos escribiendo
	set showmatch " Indica cierre de llaves
	set ruler "visualizar numero de linea y columna
  setlocal nonumber " Ocultamos número de linea en archivo.
	" set novisualbell
	set noerrorbells
	set showbreak=->  " Shows this string before broken lines
	syntax on

  "StatusLine"

  let g:gitparsedbranchname = ' '
  function! UpdateGitBranch()
    let l:string = system("git rev-parse --abbrev-ref HEAD 2>/dev/null | tr -d '\n'")
    let g:gitparsedbranchname = strlen(l:string) > 0?'['.l:string.']':''
  endfunction

  augroup UPDATE_GITBRANCH
      " clear old commands
      autocmd!

      " update git branch
      autocmd BufWritePre * :call UpdateGitBranch()
      autocmd BufReadPost * :call UpdateGitBranch()
      autocmd BufEnter * :call UpdateGitBranch()
  augroup END

  set statusline=
  " set statusline+=%#Visual#           " Color.
  " set statusline+=%#StatusLine#         " Color.
  set statusline+=%{g:gitparsedbranchname}
  set statusline+=\ %f                  " File.
  set statusline+=%=                    " Align right.
  set statusline+=\ %l:%c               " Line/column.
  hi StatusLine ctermfg=15 cterm=bold ctermbg=8

  "Colores"

	" Aquí se activa el coloreado de sintaxis (syntax highlighting), además de
	" poner algunas opciones adicionales que son cómodas para programar (ver los
	" comentarios correspondientes).

	if has("gui_running")
    colorscheme edumag
	endif

	if has("syntax") || has("gui_running")

		" El resaltado de sintaxis de algunos lenguajes tiene opciones
		" adicionales, aquí activamos las más útiles, sobre todo aquéllas que
		" señalan (normalmente en rojo) ciertos errores de programación.
		let c_gnu                = 1
		let c_space_errors       = 1
		let java_space_errors    = 1
		let ora_space_errors     = 1
		let plsql_space_errors   = 1
		let python_space_errors  = 1
		let python_highlight_all = 1
		let g:sql_type_default   = 'mysql'

	endif

  " Tipo de fuente
  " set gfn=Monospace\ 12
  set gfn=Luxi\ Mono\ 10
  " Desactivamos menu y toolbar en gui
  "set guioptions-=T  " Con barra herramientas 
  set guioptions=''  " Desactivado sin menú
  "set guioptions='mg'  " solo menú
  " Activamos menú con <Ctrl>S
  inoremap <C-S> <esc>:set guioptions=''<CR>a
  noremap <C-S> :set guioptions=''<CR>
  " Desactivamos menú con <Ctrl>D
  inoremap <C-D> <esc>:set guioptions='mg'<CR>a
  noremap <C-D> :set guioptions='mg'<CR>
  "set bg=dark

  " Con esto Vim señalará con fondo rojo los espacios que queden al final
  " de línea: rara vez sirven para algo, así que prefiero poder *verlos*
  " para poder quitarlos.
  highlight WhitespaceEOL ctermbg=235 guibg=grey50
  match WhitespaceEOL /\s\+$/

  highlight ColorColumn ctermbg=none ctermfg=red guibg=black guifg=red
  call matchadd('ColorColumn', '\%81v', 100) "set column nr

  " Color spell.
  hi clear SpellBad
  hi SpellBad cterm=underline

" SANGRADO, SALTOS DE LINEA Y TABULADORES

   " setlocal textwidth=80 " Limita el ancho a 80 caracteres.
   set tabstop=4  " ancho de tabulador estandar
   set softtabstop=4 " ancho que deseamos
   set shiftwidth=4  " ancho del sangrado
   "set foldmethod=marker  " Plegar por marcas
   set foldmarker={,} " Marcas con las que plegar
   set foldmethod=indent  " Plegar por indent
   set autoindent " Indentación automatica
   set expandtab " El tabulador utiliza espacios en blanco
   filetype indent on	" Indenta segun tipo de archivo
   set backspace=indent,eol,start	" more powerful backspacing
   set smartindent

" BÚSQUEDAS

	" set nohlsearch  " No ilumina las búsquedas encontradas
	set hlsearch  " Ilumina las búsquedas encontradas
	set ignorecase smartcase " Ignora mayúsculas en búsquedas salvo si se escribe en mayúsculas.
	set incsearch " Búsqueda incremental

" COMANDOS PROPIOS

    iab _DP echo "<pre>" ; print_r($_POST) ; echo "</pre>"; // DEV 
    " FALTA LITERAL
    ab _FT /** FALTA LITERAL **/
    ab _FECHA <esc>:read !date +"\%A, \%d de \%B del \%Y"<cr>kJ<end>a
    " Suffixes that get lower priority when doing tab completion for filenames.
    " These are files we are not likely to want to edit or read.
    set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc
    command Incloura !$HOME/desarrollo/magtrabajos/magtrabajos -a %

    " AUTOCOMMAND
    " En Vim se pueden definir comandos que se ejecutan automáticamente cuando
    " una determinada cosa ocurre. Este ejemplo hace que al cargar un fichero
    " que se había editado previamente se posiciones el cursor la línea en que
    " estaba cuando se dejó de editar por última vez. Muy cómodo :-)

    if has("autocmd")
        autocmd BufReadPost *
                    \ if line("'\"") > 0 && line("'\"") <= line("$") |
                    \		execute "normal g'\"" |
                    \ endif
    endif

    " Al abrir fichero desplegari. 
    autocmd BufWinEnter * silent! :%foldopen!

    " Forzar detectar archivos .md como markdown.
    au BufNewFile,BufFilePre,BufRead *.md set filetype=markdown

    " Syntax para rst
    au BufNewFile,BufRead *.rst set ft=rest

    " Syntax para html
    au BufNewFile,BufRead *html set ft=xml

    au BufRead,BufNewFile *.txt :setlocal spell
    au BufRead,BufNewFile *.md :setlocal spell
    au BufRead,BufNewFile *.rst :setlocal spell

" PROGRAMACIÓN

    " Barra de etiquetas a la derecha.
    let Tlist_Use_Right_Window = 1

    " Lista errores
    map <F7> :cp<CR>
    map <F8> :cn<CR>

    " Ver documentación de php.
    " Con ponerte sobre una función y pulsar ‘K’ mayúscula tendrás la documentación 
    " correspondiente.
    " Instalar la documentación en el sistema.
    " sudo pear install doc.php.net/pman
    set keywordprg=terminator\ -x\ pman 

    if has("autocmd")
    " Drupal *.modules files.
    augroup module
      autocmd BufRead *.dox set filetype=java.doxygen
    augroup END
    augroup module
      autocmd BufRead *.inc set filetype=php
    augroup END
    augroup module
      autocmd BufRead *.install set filetype=php
    augroup END
    augroup module
      autocmd BufRead *.module set filetype=php
    augroup END
    augroup engine
      autocmd BufRead *.engine set filetype=php
    augroup END
    augroup profile
      autocmd BufRead *.profile set filetype=php
    augroup END
    augroup test
      autocmd BufRead *.test set filetype=php
    augroup END
    endif

    if !exists("autocommads_loaded")
    let autocommads_loaded = 1
    " autocmd FileType html set omnifunc=htmlcomplete#CompleteTags#Html " @todo Da error falta la función.
    autocmd FileType php call Php()
    autocmd FileType javascript call Php()
    autocmd FileType txt call Txt()
    autocmd FileType rst call Rst()
    autocmd FileType rest call Txt()
    autocmd FileType sh call Sh()
    autocmd FileType css set omnifunc=csscomplete#CompleteCSS
    endif

    " Autocommands para PHP
    function Php() 

      setlocal textwidth=80 " Limita el ancho a 80 caracteres.
      " Compilador tidy
      " compiler tidy
      " UTF8 para archivos php
      " set encoding=utf8
      " Con Ctrl-r comentamos la linea y la copiamos abajo
      inoremap <C-R> <Esc>yyg^i//<Esc>pi
      " Con esta opción el texto sera cortado en la columna indicada por
      " *textwidth* con formatoptions=croql hara que el codigo fuente no sea
      " formateado pero si los comentarios
      setlocal fo-=t fo+=croql
      " Don't concatenate a line that ends with a backslash
      setlocal cpo-=C
      set autoindent " Indentación automatica
    endfunction

    function Rst()
    setlocal textwidth=80 " Limita el ancho a 80 caracteres.
    setlocal fo=cqt
    setlocal wm=1
    endfunction

    function Txt()
    setlocal textwidth=80 " Limita el ancho a 80 caracteres.
    setlocal fo=cqt
    setlocal wm=1
    endfunction

    function Sh()
    set foldmethod=marker  " Plegar por marcas
    "set foldmethod=indent  " Plegar por indent
    setlocal textwidth=0 " Quita limitacion de caracteres.
    " Con Ctrl-r comentamos la linea y la copiamos abajo
    inoremap <C-R> <Esc>yyg^i# <Esc>pi
    " Ejecutar el script editado con ALT-e, sirve para scripts bash
    noremap! å :w :!% i
    endfunction

    " python
    autocmd FileType python set sw=4
    autocmd FileType python set ts=4
    autocmd FileType python set sts=4
    " AutoPep8, dando formato a python. 
    " sudo pip install autopep8
    " Seleccionamos texto y tecleamos "gq".
    au FileType python setlocal formatprg=autopep8\ -

" COLORES EN CSS

  "Is used when updatetime value set by plugin (100ms) 
  "is interfering with your configuration.
  " g:cssColorVimDoNotMessMyUpdatetime
  let g:cssColorVimDoNotMessMyUpdatetime = 1

" PLUGINS

    " PHP_CodeSniffer.
    Plugin 'phpcs.vim'
    " Activamos revisión de código Al leer o guardar fichero.
    " autocmd BufRead *.php :Phpcs
    let g:phpcs_std_list   = "PSR2"
    let g:phpcs_max_output = 0 " Unlimited output.

    " AIRLINE
    " Plugin 'vim-airline/vim-airline'
    " Plugin 'vim-airline/vim-airline-themes'
    " let g:airline_theme='angr'
    " " set laststatus=2
    " let g:airline_powerline_fonts=1
    " " Habilita los tabs, para cambiar de tab presionar gt
    " let g:airline#extensions#tabline#enabled = 0
    " " Enable the list of buffers
    " let g:airline#extensions#tabline#show_buffers = 0
    " let g:airline#extensions#tabline#show_tabs = 0
    " " set t_Co=256
    " let g:airline#extensions#branch#enabled=0
    " let g:airline#extensions#hunks#enabled=0
    "   " let g:airline_extensions = ['branch', 'tabline']

    " Debug
    " Plugin 'joonty/vdebug'

    " Abrir archivos.
    " Pulsando Ctrl+P el pluguin nos permite ir viendo los archivos que 
    " coinciden con el texto que vamos tecleando.
    " Con ctrl+z podemos marcar los que queramos abrir y con ctrl+o abrirlos.
    " Plugin 'ctrlp.vim'

    " Python Mode.
    Plugin 'Python-mode-klen'
    let g:pymode_options = 0
    let g:pymode_lint = 1
    " let g:pymode_lint_ignore="E302,E266,W0401,E501,C901,E221"
    let g:pymode_trim_whitespaces = 1
    setlocal complete+=t
    setlocal formatoptions-=t
    " if v:version > 702 && !&relativenumber
    "     setlocal nonumber
    " endif
    setlocal nowrap
    setlocal textwidth=79
    setlocal commentstring=#%s
    setlocal define=^\s*\\(def\\\\|class\\)
    let g:pymode_virtualenv = 1

    " Varios.
    Plugin 'rest.vim'
    Plugin 'sukima/xmledit'

    " Plugin 'chrisbra/csv.vim'
    " let did_load_csvfiletype=1
    " au BufNewFile,BufFilePre,BufRead *.csv set filetype=csv

    " Typescript
    " https://www.vimfromscratch.com/articles/setting-up-vim-for-typescript
    "" Plugin 'leafgarland/typescript-vim'
    "" " let g:typescript_indent_disable = 1
    "" au BufNewFile,BufFilePre,BufRead *.ts set filetype=typescript
    "" Plugin 'sbdchd/neoformat'
    "" autocmd FileType typescript setlocal formatprg=prettier\ --parser\ typescript
    "" " Ale
    "" " Demasiados recursos, desactivo.
    "" " Plugin 'w0rp/ale'
    "" " let g:ale_fixers = {}
    "" " let g:ale_fixers.javascript = ['eslint']
    "" " let g:ale_fix_on_save = 1

    " Tabulación.
    " :Tab /=
    Plugin 'godlygeek/tabular'

    " Colores css.
    Plugin 'ap/vim-css-color'

    "" Vue
    " Vim syntax highlighting for [Vue
    Plugin 'posva/vim-vue'
    " let g:vue_pre_processors = 'detect_on_enter'
    if has("autocmd")
    augroup vue
      autocmd BufRead *.vue set filetype=vue
    augroup END
    endif
    " Syntax and indent plugin.
    Plugin 'leafOfTree/vim-vue-plugin'
    let g:vim_vue_plugin_config_load_full_syntax = 1
    let g:vim_vue_plugin_config_use_typescript = 0


    " https://github.com/junegunn/fzf/blob/master/README-VIM.md
    Plugin 'junegunn/fzf'
    set rtp+=~/.fzf/bin
    map <C-P> <esc>:FZF!<CR>
